a.out: main.o cancel_ticket.o booking_details.o reserve_ticket.o display_trains_with_availability.o display_trains.o next_free_seat.o available_seats.o booked_count.o validity.o signin.o user_menu.o signup.o admin_menu.o add_train.o train_exists.o valid_password.o file_init.o
	cc main.o cancel_ticket.o booking_details.o reserve_ticket.o display_trains_with_availability.o display_trains.o next_free_seat.o available_seats.o booked_count.o validity.o signin.o user_menu.o signup.o admin_menu.o add_train.o train_exists.o valid_password.o file_init.o -o a.out

main.o: main.c
	cc -c main.c
cancel_ticket.o: cancel_ticket.c
	cc -c cancel_ticket.c
booking_details.o: booking_details.c
	cc -c booking_details.c
reserve_ticket.o: reserve_ticket.c
	cc -c reserve_ticket.c
display_trains_with_availability.o: display_trains_with_availability.c
	cc -c display_trains_with_availability.c
display_trains.o: display_trains.c
	cc -c display_trains.c
next_free_seat.o: next_free_seat.c
	cc -c next_free_seat.c
available_seats.o: available_seats.c
	cc -c available_seats.c
booked_count.o: booked_count.c
	cc -c booked_count.c
validity.o: validity.c
	cc -c validity.c
signin.o: signin.c
	cc -c signin.c
user_menu.o: user_menu.c
	cc -c user_menu.c
signup.o: signup.c
	cc -c signup.c
admin_menu.o: admin_menu.c
	cc -c admin_menu.c
add_train.o: add_train.c
	cc -c add_train.c
train_exists.o: train_exists.c
	cc -c train_exists.c
valid_password.o: valid_password.c
	cc -c valid_password.c
file_init.o: file_init.c
	cc -c file_init.c
clean: 
	rm -f *.o a.out


